<?php

namespace Database\Seeders;

use App\Models\Admin\Tag;
use App\Models\Admin\Admin;
use App\Models\Admin\Article;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Admin::find(5)->articles()->saveMany(Article::factory(30)->make());      
        $articles = array(
            array('id' => '1', 'title' => 'nihil.', 'body' => 'Ea qui dolores a rerum placeat et modi. Doloribus est officiis molestias non sit. Doloremque voluptas officiis dignissimos ducimus dolor est delectus voluptatem. Voluptatem illo numquam adipisci aut. Cumque ad qui voluptatem sit minima. Aut nemo ab aut consequuntur sequi. Sed a ut mollitia fuga explicabo. Quam alias dicta voluptate non vitae. Eum fuga est ad. Beatae quisquam accusamus consequatur ut et magni.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'ea6cc0c503af5ce04695cefc347719e1.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'nihil', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '2', 'title' => 'animi.', 'body' => 'Optio rerum deserunt ea eligendi. Sunt ex delectus odio impedit. Minima praesentium itaque dolores est dolore. Quo temporibus quidem magnam quo. Aut accusamus amet et sed delectus. Qui minus sunt quia et in perferendis. Exercitationem repellat et quia at esse sunt. Ut eligendi animi corporis eum. Incidunt accusamus eos earum. Vero quia et dolores quia praesentium maxime quod.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'f4fcea6adce115357dab14f3c635c643.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'animi', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '3', 'title' => 'harum id.', 'body' => 'Quis esse voluptatem est facilis. Nihil ipsum corrupti quam corrupti odio. Aut molestiae necessitatibus architecto quae. Doloribus ab qui aliquam voluptatibus cupiditate. Est commodi laboriosam aut ad et est aspernatur. Magni ratione odit assumenda libero quidem. At minima reprehenderit tempore quod quaerat non qui. Iusto molestiae maxime quia quod in. Ipsa alias beatae quo voluptas. Non tempore asperiores in culpa.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '2353fa12bb0d949fd3c61334f20b69b8.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'harum-id', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '4', 'title' => 'aliquid.', 'body' => 'Quia illum saepe quo aut autem voluptate sit. Veniam corporis quisquam quia. Enim impedit porro et omnis sit sunt. Ipsum doloremque velit magnam libero. Voluptatem consequatur voluptatem odit. Inventore repellat velit minus et sint. Reprehenderit sint debitis voluptas velit. Tenetur voluptatem aliquid tenetur esse quasi maiores dolorum. Assumenda voluptates quas reiciendis ut sint nemo qui. Unde vel temporibus quia. Eveniet ipsa dolorem suscipit quia adipisci.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '2e2f33d72a5e55bb94cdb2ec4ec0a6ef.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'aliquid', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '5', 'title' => 'officia.', 'body' => 'Cumque odio rerum autem. Et est amet ad deserunt. Architecto dolore magni voluptatibus explicabo molestiae. Quidem quisquam exercitationem est commodi voluptatem maiores. Eos qui veritatis aut blanditiis sunt aliquam. Delectus eum ea eos cumque quos. Sed sed praesentium maxime dolores earum. Aperiam error quia ipsam in porro et consequuntur qui. Rerum cum blanditiis consequatur accusamus et. Vitae ut sed molestiae aut molestiae molestiae. Alias dolorem beatae harum quod eos sed.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '907be2622e1c28ed51685b296e4f9fed.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'officia', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '6', 'title' => 'sunt nemo.', 'body' => 'Praesentium corporis nam non consequatur. Adipisci saepe occaecati aliquam odit deserunt qui dolorem et. Praesentium dolorem voluptatibus dolorem nihil et ducimus iure quia. Itaque delectus ea quos qui sint. Illo sunt atque explicabo corrupti quaerat reiciendis debitis. Nulla at ut quia laborum et odio eveniet dolores. Impedit sit nam labore reiciendis laboriosam odit.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '8c81d157c0b2d7a618b6f33f2a86a08f.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'sunt-nemo', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '7', 'title' => 'sed.', 'body' => 'Adipisci voluptas vel consequatur quae molestiae. Consequatur illum consequatur molestias voluptates quidem. Dolor qui dolores impedit ex quaerat. Qui recusandae corrupti exercitationem iure ratione reprehenderit. Sint repellendus consequuntur dolorem ut dolor facere. Quo sint saepe nesciunt doloremque perferendis. Eligendi dolores eum aut minima sapiente. Earum facere quaerat adipisci harum et vel ullam possimus.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '0', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'sed', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '8', 'title' => 'ea.', 'body' => 'Fugiat commodi cumque eveniet quis magnam. Consequatur autem minus dicta. Velit non qui aut facere dolor similique porro. Possimus at expedita minima esse. Nihil quam delectus quod vel atque ipsum explicabo. Id qui et suscipit consequatur ex culpa. Itaque corrupti autem corporis voluptas iste. Explicabo perspiciatis sit fugiat repellat sint aut.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'ca89c63daf4d51ad30eb72bd234fb39b.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'ea', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '9', 'title' => 'animi at.', 'body' => 'Facilis aut quo sequi et. Officia ut reprehenderit rerum. Atque aut minus corrupti mollitia. Placeat enim libero omnis vel asperiores rem impedit. Ipsam eos non qui architecto quaerat veritatis voluptatibus praesentium. Expedita vel consequatur nisi consequuntur vitae. Accusamus similique ut vitae. Ut modi praesentium quia perspiciatis natus non repellendus. Eum ut qui ducimus nam voluptas nisi.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '6f951afb649eed811ad6cc2fadd69732.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'animi-at', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '10', 'title' => 'sed rerum.', 'body' => 'Est ab voluptates sit tempore est dolores quas. Omnis quibusdam modi et occaecati. Maxime laboriosam totam aliquam ipsa eaque. Vitae tenetur iure repellendus iure eaque aut vitae. Labore praesentium quidem esse animi repellendus impedit porro voluptatem. Optio pariatur et praesentium cupiditate eos aspernatur. Possimus totam voluptates qui eos dolore. Sit sunt atque expedita distinctio et dolore est atque.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'ae9211f9262dcae8daff62e76ae1035f.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'sed-rerum', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '11', 'title' => 'excepturi.', 'body' => 'Similique qui consequatur eaque deleniti eum saepe vero est. Rem facilis non explicabo omnis. Temporibus similique id ullam delectus quo quis. Porro ducimus quia laudantium neque dolor. Rem hic dolores ex quia deserunt laboriosam et. Voluptatem fugit voluptatem incidunt dolore. Laboriosam doloribus ipsa deleniti ipsa consequuntur voluptatem commodi. Deserunt illum velit omnis excepturi dolorum molestias.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '8b0b7a0c2c7e60177875254a189d8d80.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'excepturi', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '12', 'title' => 'quia ea.', 'body' => 'Omnis veniam sequi eum delectus aut qui placeat. Omnis facere consequatur vitae ex aut ipsa ut deserunt. Consequatur quisquam adipisci saepe. Aut repellendus excepturi rerum asperiores quasi ab aut. Voluptates eaque maiores hic. Dolorum in in quaerat omnis ipsum vero quidem. Rem et eligendi est itaque doloribus est. Quia ea libero voluptate. Quaerat dolorem laudantium magni dolor voluptatum commodi. Soluta eligendi et qui molestias minima voluptatem nam et.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '5b48efe57bb6f582880c19653016fb29.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'quia-ea', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '13', 'title' => 'iure.', 'body' => 'Non reprehenderit quia magni sit iusto sed qui. Temporibus quae laboriosam exercitationem eligendi omnis consectetur nemo. Sapiente corporis sequi sequi quaerat qui. Aut et rem nam quisquam non voluptates cupiditate. Nihil doloremque et illum vero laborum sed asperiores veritatis. Occaecati voluptas fugit qui iusto dolor est.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'a558d518f59b44b69004d240121f07a4.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'iure', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '14', 'title' => 'et quod.', 'body' => 'Itaque quasi molestiae in esse fuga dolores. Perspiciatis et consequatur illum vel quis repellendus. Vel dolorem est mollitia quaerat dolor quo praesentium. Numquam voluptate earum ut quam ex qui. Ab magni voluptatem esse nostrum magni iusto eius. Ea deleniti nulla consequatur hic vel. Et voluptatem omnis placeat adipisci ducimus alias. Beatae magni minima illo eos dignissimos aliquam aut. Hic et sunt pariatur enim ex doloribus.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'a7917b56d8d9e717c421a05cec11de7f.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'et-quod', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '15', 'title' => 'iusto.', 'body' => 'Facere et sit non quos deserunt explicabo asperiores. Iure porro laboriosam aut. Praesentium accusantium eum est quam omnis eveniet amet at. Nihil qui sapiente in eum. Est ut asperiores excepturi rerum. Nobis aut corrupti ratione deleniti quas. Laudantium quia natus voluptatibus quos et sapiente. Ea recusandae nostrum enim expedita harum quia. Nemo tempore nulla sint blanditiis. Cum quae nemo doloremque reprehenderit. Sapiente commodi optio similique id nisi.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '03a83edabc61f939563c1e1009c30c70.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'iusto', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '16', 'title' => 'commodi.', 'body' => 'Quam aut eveniet quod. Omnis suscipit molestias voluptatem ducimus vero. Veritatis ipsam maxime omnis sed a totam tenetur. Maiores assumenda dicta aspernatur ab est ad quia. Accusantium eum magni ea quo est sint vel. Dolore laborum explicabo doloremque aut aut officiis. Soluta omnis et quisquam sed optio et iste. Perferendis sint earum quis maxime aut dolores. Sit eos cupiditate et eum non. Quae suscipit qui aspernatur voluptatibus tempora qui nostrum. Eum sequi deleniti ut sint perspiciatis.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '4a9987974b6d93b35d7da782bf0e9406.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'commodi', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '17', 'title' => 'itaque.', 'body' => 'Eaque ipsa fuga dicta sint. Voluptatem totam voluptas unde voluptatem voluptatum accusamus. Repellendus consequatur sed eos fugiat dolor. Reprehenderit in natus numquam quaerat dignissimos eum non cupiditate. Quia quasi quaerat voluptatem itaque nihil ducimus. Unde accusamus repellendus illo adipisci quos nihil voluptatem deleniti. Harum aut aut numquam eos doloribus. Alias vero soluta laborum doloremque ut voluptas. Iusto et alias voluptatibus sunt et ducimus est.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '24db69fb474b830971405a52b3b907da.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'itaque', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '18', 'title' => 'eum.', 'body' => 'Quos beatae ut dolorum aspernatur. Necessitatibus aut incidunt quo dolores neque odit est. Consectetur expedita iure dolores similique. Ut et ut non nihil non perferendis. Ut iste optio dolorem est sint. Dolorum earum natus qui saepe architecto ut. Fugiat doloremque enim suscipit. Modi libero fuga deleniti reiciendis eum quo expedita. Enim sapiente veritatis consequatur placeat.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'c6e7c96ba4e5b99f6e7953cf7e67e4c2.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'eum', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '19', 'title' => 'placeat.', 'body' => 'Sequi rem aut in qui accusantium suscipit. Sunt voluptatem qui sint omnis amet mollitia. Corrupti commodi nulla iusto odio voluptas. Placeat reiciendis aut et nihil et maiores dolorem. Ut tenetur ab consequatur qui. Corporis aut ea nihil error aliquam aut tenetur. Quas et possimus eos occaecati. Sint consequatur quisquam in ipsum soluta aspernatur aspernatur. Magnam aut minus eaque expedita. Esse dolor quo eligendi modi perspiciatis ut at dolorem.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'fd9030c3be37109d7a3512fb111a285b.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'placeat', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '20', 'title' => 'ad libero.', 'body' => 'Cupiditate minima architecto recusandae rerum. Qui velit odio cumque aliquid delectus quo reprehenderit. Modi quia impedit voluptatem. Reiciendis facilis quod rem sapiente sed voluptatibus quia et. Aliquid fuga nihil ratione id aspernatur. Labore consectetur modi nemo. Qui accusamus ipsa sed impedit. Possimus accusamus perferendis eligendi deleniti. Dolorem esse ducimus debitis ducimus cupiditate in sunt expedita. Veniam sunt ipsam saepe modi.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '7e4d616b330e3ace3524e8480dbcb701.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'ad-libero', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '21', 'title' => 'ipsum.', 'body' => 'Est dolorem quas in deleniti eos vitae. Ex nisi quas repudiandae libero debitis iste. Magnam voluptatem iure ducimus eius. Ut aut ducimus nihil mollitia. Rerum accusantium laudantium non sunt. Saepe nemo excepturi voluptatibus quos et. Praesentium a non rerum repellat et sint. Ratione facere quidem architecto at ea ea iure. Placeat quia maiores fugiat animi. Quaerat ut et id quis eos quidem error. Est voluptate facere assumenda minima officiis.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '3c718e9484b8798ece6007b6951a8b55.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'ipsum', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '22', 'title' => 'hic.', 'body' => 'Et voluptatem praesentium pariatur vitae qui iusto veniam. Soluta sunt laudantium aspernatur dolores corrupti voluptates et odit. Qui sed sint ea aut. Et facere numquam non possimus ut illo. Illo et est est animi sunt provident. Inventore eaque dolores inventore ut. Recusandae totam illo qui deserunt dolorem.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '1d2b75e037011b9fb8f429abc1488eaa.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'hic', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '23', 'title' => 'et.', 'body' => 'Repellat dolorum reprehenderit est dolorem dolorem. Quia praesentium voluptatum ea atque. Voluptas quo saepe impedit exercitationem voluptas. Eos id sint totam iusto enim debitis est. Placeat qui quia quasi qui vel voluptatem. Qui et quisquam sint necessitatibus. Quod dolor qui similique. Ab voluptas maxime eos impedit. Non voluptates voluptatem est molestiae libero vitae quia. Doloremque et aut qui.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'f801c471b92a4be3348a4e274e10cb4f.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'et', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '24', 'title' => 'tempore.', 'body' => 'Nemo eos temporibus quia non possimus aliquam. Sint molestiae ab veniam saepe. Quis est corporis voluptatem doloribus sint quia. Explicabo possimus sint qui reiciendis doloribus eum voluptatem. Ratione aut enim exercitationem et. Reiciendis ad nostrum saepe debitis. Labore consequuntur aperiam ipsam ut. Vel sed molestiae nobis sit velit nemo.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '68528a852e2db9bb856e8c21f879fcdf.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'tempore', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '25', 'title' => 'sed autem.', 'body' => 'Debitis doloribus et reprehenderit blanditiis. Eligendi doloremque non odio minus voluptas. Nostrum amet suscipit non eos aut officia. Ut eligendi similique tenetur et fugit ab numquam. Quibusdam voluptatum nihil totam eius ratione. Quaerat ut voluptate autem omnis. Labore vel reprehenderit quas nihil sit. Sed sed quos omnis veritatis neque. Explicabo qui ab aspernatur velit beatae quod.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '2eb8010aa8abdda30bd8bc98e2c7065a.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'sed-autem', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '26', 'title' => 'est illum.', 'body' => 'Praesentium dolor est soluta dolorem necessitatibus beatae. Omnis dignissimos aspernatur eum nihil. Quo numquam fuga nihil ab. Vel sint nobis ut quas quidem. Similique dolore rerum officia expedita repudiandae illum. Accusamus qui officia consequuntur ullam perferendis vel eligendi. Odio veniam porro in facilis. Fuga autem porro ea praesentium quibusdam doloremque. Enim blanditiis praesentium aliquam earum quaerat sed excepturi.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'ae4d59c8b66f14521c50391831a47179.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'est-illum', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '27', 'title' => 'quisquam.', 'body' => 'Esse alias alias sit ab aperiam totam fuga. Recusandae autem consectetur voluptatibus occaecati ut et. Ea deleniti inventore provident et rerum cumque. Consectetur ea nemo dolore qui et. Quis et dolor officiis maiores quod quae eius quia. Laudantium et rerum doloremque tenetur consequatur saepe. Asperiores tenetur a eligendi quidem voluptatem saepe. Et et et illum consequatur sed ut.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '8bcbda7306b6763f64cd395a6f2a35f7.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'quisquam', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '28', 'title' => 'corrupti.', 'body' => 'Vero corrupti nobis nisi sint. Aperiam eius perspiciatis labore dolores. Dolore sunt maiores corporis et. Repudiandae a dolor amet sit eaque odio debitis ut. Quae ex quidem alias sed occaecati. Repudiandae consequatur fuga quo omnis inventore. Voluptatum omnis rerum dolorem vel mollitia. Sint distinctio provident cum ullam quia quas. Voluptas ratione tempore error sint ipsam atque ut. Odio itaque in corporis molestias rerum delectus veritatis.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'a0499dec7049995b3d4f15e809ab5627.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'corrupti', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '29', 'title' => 'sequi eum.', 'body' => 'Quisquam ipsam quod qui qui iure architecto voluptate. Inventore quaerat ipsam sit alias quas. Et repellat mollitia consequatur fugit suscipit. Fuga aliquid qui voluptatem. Rerum architecto voluptas est aut blanditiis facere. Sint rerum aliquam nihil deserunt eveniet recusandae doloremque. Id rem vero perferendis esse. Expedita modi est facilis laudantium. Rem quia ex quaerat consectetur sapiente dignissimos.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => 'c50bd6457496e2bbc440e022c12cbda8.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'sequi-eum', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47'),
            array('id' => '30', 'title' => 'quis.', 'body' => 'Iste delectus deserunt voluptatem nihil. Recusandae qui fugit ipsam et impedit. Dicta facere laboriosam vitae. Quo autem est et rem fugiat itaque in. Quis eos enim magnam veniam et. Sapiente error quia ratione aliquid natus ea. Totam dolorem velit vel ab. A autem eveniet doloribus dolor. Libero quae qui earum nobis deleniti cupiditate. Mollitia dolores omnis blanditiis. A neque dolorem non sit voluptates et.', 'excerpt' => NULL, 'priority' => '1', 'status' => '1', 'published_at' => '2023-04-10', 'imageOne' => '4a5bcc4158aa374a6c35b838715170cf.png', 'imageGallery' => ["article1.png", "article2.png", "article3.png", "article4.png", "article5.png"], 'category_id' => NULL, 'likes' => '30', 'slug' => 'quis', 'articable_type' => 'App\\Models\\Admin\\Admin', 'articable_id' => '5', 'deleted_at' => NULL, 'created_at' => '2023-04-10 08:44:47', 'updated_at' => '2023-04-10 08:44:47')
        );

        $admin = Admin::find(5);
        foreach ($articles as $key => $val) {
            $admin->articles()->create($val);
        }
        Article::all()->each(function ($article) {
            $article->tags()->attach(Tag::inRandomOrder()->take(rand(1, 9))->get());
        });
    }
}
