<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\TaskMaster;
use App\Models\Admin\TaskTimeline;
use App\Models\Member\MemberDepartment;

class TaskMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $taskcats = array(
            array('id' => '1', 'name' => 'Wedding Planning', 'description' => 'Planning of Wedding Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '2', 'completionDate' => '2023-04-08', 'icon' => 'wedding-planning.svg', 'imageOne' => 'wedding-planning.png', 'slug' => 'wedding-planning', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '2', 'name' => 'Wedding Venues', 'description' => 'Wedding Venues', 'status' => '1', 'priority' => '0', 'timeline_id' => '2', 'completionDate' => '2023-04-08', 'icon' => 'wedding-venues.svg', 'imageOne' => 'wedding-venues.png', 'slug' => 'wedding-venues', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '3', 'name' => 'Accommodation', 'description' => 'Wedding Guests Acomodation Providers', 'status' => '1', 'priority' => '0', 'timeline_id' => '3', 'completionDate' => '2023-04-08', 'icon' => 'accommodation.svg', 'imageOne' => 'accommodation.png', 'slug' => 'accommodation', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '4', 'name' => 'Invitation Cards', 'description' => 'Wedding Card Designs', 'status' => '1', 'priority' => '0', 'timeline_id' => '3', 'completionDate' => '2023-04-08', 'icon' => 'invitation-cards.svg', 'imageOne' => 'invitation-cards.png', 'slug' => 'invitation-cards', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '5', 'name' => 'Catering', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'catering.svg', 'imageOne' => 'catering.png', 'slug' => 'catering', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '6', 'name' => 'Entertainment', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'entertainment.svg', 'imageOne' => 'entertainment.png', 'slug' => 'entertainment', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '7', 'name' => 'Flower Decorators', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'flower-decorators.svg', 'imageOne' => 'flower-decorators.png', 'slug' => 'flower-decorators', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '8', 'name' => 'Health and Beauty', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'health-and-beauty.svg', 'imageOne' => 'health-and-beauty.png', 'slug' => 'Health-and-beauty', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '9', 'name' => 'Jewellery', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'jewellery.svg', 'imageOne' => 'jewellery.png', 'slug' => 'jewellery', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '10', 'name' => 'Transportation', 'description' => 'Planning of Marriage Activites and Tasks', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'transportation.svg', 'imageOne' => 'transportation.png', 'slug' => 'transportaion', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '11', 'name' => 'Wedding Stationery', 'description' => 'Wedding Stationery', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'wedding-stationery.svg', 'imageOne' => 'wedding-stationery.png', 'slug' => 'wedding-stationery', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '12', 'name' => 'Favors & Gifts', 'description' => 'Wedding Favors and Gifts Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'favors-gifts.svg', 'imageOne' => 'favors-gifts.png', 'slug' => 'favors-and-gifts', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '13', 'name' => 'Groom Styles and Wears', 'description' => 'Wedding Groom Styles and Wear Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'groom-styles-and-wears.svg', 'imageOne' => 'groom-styles-and-wears.png', 'slug' => 'groom-styles-and-wears', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '14', 'name' => 'Bride Styles and Wears', 'description' => 'Wedding Bride Styles and Wear Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bride-styles-and-wears.svg', 'imageOne' => 'bride-styles-and-wears.png', 'slug' => 'bride-styles-and-wears', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '15', 'name' => 'Wedding Decors', 'description' => 'Wedding Decors Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'wedding-decors.svg', 'imageOne' => 'wedding-decors.png', 'slug' => 'wedding-decors', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:38', 'updated_at' => '2023-06-04 18:47:38', 'deleted_at' => NULL),
            array('id' => '16', 'name' => 'Bartenders', 'description' => 'Wedding Bartenders Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bartenders.svg', 'imageOne' => 'bartenders.png', 'slug' => 'bartenders', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '17', 'name' => 'Clothing Rentals', 'description' => 'Wedding Clothing Rentals Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'clothing-rentals.svg', 'imageOne' => 'clothing-rentals.png', 'slug' => 'clothing-rentals', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '18', 'name' => 'Cakes', 'description' => 'Wedding Cakes Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'cakes.svg', 'imageOne' => 'cakes.png', 'slug' => 'cakes', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '19', 'name' => 'Choreographers', 'description' => 'Wedding Choreographers Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'choreographers.svg', 'imageOne' => 'choreographers.png', 'slug' => 'choreographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '20', 'name' => 'Photographers', 'description' => 'Wedding Photographers', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'photographers.svg', 'imageOne' => 'photographers.png', 'slug' => 'photographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '21', 'name' => 'PreShoot Photographers', 'description' => 'Wedding PreShoot Photographers', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'preshoot-photographers.svg', 'imageOne' => 'preshoot-photographers.png', 'slug' => 'preshoot-photographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '22', 'name' => 'PreShoot Videographers', 'description' => 'Wedding Preshoot Video Graphers', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'preshoot-videographers.svg', 'imageOne' => 'preshoot-videographers.png', 'slug' => 'preshoot-videographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '23', 'name' => 'VideoGraphers', 'description' => 'Wedding Video Graphers', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'videographers.svg', 'imageOne' => 'videographers.png', 'slug' => 'videographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '24', 'name' => 'Groom Makeup Artists', 'description' => 'Wedding Makeup Artists Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'groom-makeup-artists.svg', 'imageOne' => 'groom-makeup-artists.png', 'slug' => 'groom-makeup-artists', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '25', 'name' => 'Bridal Makeup Artists', 'description' => 'Wedding Bridal Makeup Artists Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bridal-makeup-artists.svg', 'imageOne' => 'bridal-makeup-artists.png', 'slug' => 'bridal-makeup-artists', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '26', 'name' => 'Family Makeup Artists', 'description' => 'Wedding Family Makeup Artists Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'family-makeup-artists.svg', 'imageOne' => 'family-makeup-artists.png', 'slug' => 'family-makeup-artists', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '27', 'name' => 'Wedding Stylists and  Designers', 'description' => 'Wedding Stylists and Designer Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'wedding-stylists-and-designers.svg', 'imageOne' => 'wedding-stylists-and-designers.png', 'slug' => 'wedding-stylists-and-designers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '28', 'name' => 'Bridal Mehndi Artists', 'description' => 'Wedding Bridal Mehndi Artists Description', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bridal-mehndi-artists.svg', 'imageOne' => 'bridal-mehndi-artists.png', 'slug' => 'bridal-mehndi-artists', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '29', 'name' => 'Home Catering', 'description' => 'Home Catering', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'home-catering.svg', 'imageOne' => 'home-catering.png', 'slug' => 'home-catering', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '30', 'name' => 'Chaat & Food Stalls', 'description' => '', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'chaat-food-stalls.svg', 'imageOne' => 'chaat-food-stalls.png', 'slug' => 'chaat-and-food-stalls', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '31', 'name' => 'Bandbaja', 'description' => '', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bandbaja.svg', 'imageOne' => 'bandbaja.png', 'slug' => 'bandbaja', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '32', 'name' => 'Car Rental Service', 'description' => 'Wedding Transport and Car Retnal Service', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'car-rental-service.svg', 'imageOne' => 'car-rental-service.png', 'slug' => 'car-rental-service', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '33', 'name' => 'Bridal Jewellery', 'description' => 'Wedding Bridal Jewellery', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bridal-jewellery.svg', 'imageOne' => 'bridal-jewellery.png', 'slug' => 'bridal-jewellery', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '34', 'name' => 'Bridal Jewellery On Rent', 'description' => 'Wedding Bridal Jewellery on Rent', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'bridal-jewellery-on-rent.svg', 'imageOne' => 'bridal-jewellery-on-rent.png', 'slug' => 'bridal-jewellery-on-rent', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '35', 'name' => 'Wedding Priests', 'description' => 'Wedding Pandits', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'wedding-priests.svg', 'imageOne' => 'wedding-priests.png', 'slug' => 'wedding-priests', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '36', 'name' => 'Lighting designers', 'description' => 'Wedding Lighting Designers', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'lighting-designers.svg', 'imageOne' => 'lighting-designers.png', 'slug' => 'lighting-designers', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '37', 'name' => 'Anchors', 'description' => 'Wedding Anchors', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'anchors.svg', 'imageOne' => 'anchors.png', 'slug' => 'anchors', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '38', 'name' => 'Ghoriwala , Baggi & Palki wale', 'description' => 'Goriwala, Baggi & Palki Wale', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'ghoriwala-baggi-palki-wale.svg', 'imageOne' => 'ghoriwala-baggi-palki-wale.png', 'slug' => 'ghoriwala-baggi-and-palkiwale', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '39', 'name' => 'DJ/ Musicians/ Entertainment', 'description' => 'DJ, Musicians and Entertainment Artist Groups', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'dj-musicians-entertainment.svg', 'imageOne' => 'dj-musicians-entertainment.png', 'slug' => 'dj-musicians-entertainment', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '40', 'name' => 'Honeymoon Planners', 'description' => 'Honeymoon Planners', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'honeymoon-planners.svg', 'imageOne' => 'honeymoon-planners.png', 'slug' => 'honeymoon-planners', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '41', 'name' => 'Honeymoon Packages', 'description' => 'Honeymonn Packages', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'honeymoon-packages.svg', 'imageOne' => 'honeymoon-packages.png', 'slug' => 'honeymoon-packages', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '42', 'name' => 'Security Services', 'description' => '', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'security-services.svg', 'imageOne' => 'security-services.png', 'slug' => 'security-services', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '43', 'name' => 'miscellenous tasks', 'description' => '', 'status' => '1', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'security-services.svg', 'imageOne' => 'security-services.png', 'slug' => 'miscellenous-tasks', 'path' => NULL, 'relation' => NULL, 'parent_id' => NULL, 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:47:39', 'deleted_at' => NULL),
            array('id' => '44', 'name' => 'Check if your wedding date is on an auspicious day', 'description' => 'Check if your wedding date is on an auspicious day', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-if-your-wedding-date-is-on-an-auspicious-day.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-if-your-wedding-date-is-on-an-auspicious-day', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '45', 'name' => 'Do you want a destination wedding?', 'description' => 'Do you want a destination wedding?', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'do-you-want-a-destination-wedding.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'do-you-want-a-destination-wedding', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '46', 'name' => 'Short list date options for all pre-wedding functions', 'description' => 'Short list date options for all pre-wedding functions', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'short-list-date-options-for-all-pre-wedding-functions.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'short-list-date-options-for-all-pre-wedding-functions', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '47', 'name' => 'Decide whether or not you"d like to use a wedding planner', 'description' => 'Decide whether or not you"d like to use a wedding planner', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'decide-whether-or-not-youd-like-to-use-a-wedding-planner.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'decide-whether-or-not-youd-like-to-use-a-wedding-planner', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '48', 'name' => 'Confirm wedding style', 'description' => 'Confirm wedding style', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'confirm-wedding-style.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'confirm-wedding-style', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '49', 'name' => 'Learn about different wedding styles', 'description' => 'Learn about different wedding styles', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'learn-about-different-wedding-styles.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'learn-about-different-wedding-styles', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '50', 'name' => 'Fill in missing addresses on the guest list', 'description' => 'Fill in missing addresses on the guest list', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'fill-in-missing-addresses-on-the-guest-list.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'fill-in-missing-addresses-on-the-guest-list', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '51', 'name' => 'Send out e-invites using our guest list tool', 'description' => 'Send out e-invites using our guest list tool', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'send-out-e-invites-using-our-guest-list-tool.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'send-out-e-invites-using-our-guest-list-tool', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '52', 'name' => 'Religious Wedding: Book appointment with priest / pandit etc.', 'description' => 'Religious Wedding: Book appointment with priest / pandit etc.', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'religious-wedding-book-appointment-with-priest-pandit-etc.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'religious-wedding-book-appointment-with-priest-pandit-etc', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '53', 'name' => 'Finalize the priest/pandit', 'description' => 'Finalize the priest/pandit', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'finalize-the-priestpandit.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'finalize-the-priestpandit', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '54', 'name' => 'Check wedding invitation inspirations and designs', 'description' => 'Check wedding invitation inspirations and designs', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-wedding-invitation-inspirations-and-designs.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-wedding-invitation-inspirations-and-designs', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '55', 'name' => 'Check RSVPs and follow up with the unconfirmed guests on guest list tool', 'description' => 'Check RSVPs and follow up with the unconfirmed guests on guest list tool', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-rsvps-and-follow-up-with-the-unconfirmed-guests-on-guest-list-tool.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-rsvps-and-follow-up-with-the-unconfirmed-guests-on-guest-list-tool', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '56', 'name' => 'Gather vendors for a venue visit', 'description' => 'Gather vendors for a venue visit', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'gather-vendors-for-a-venue-visit.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'gather-vendors-for-a-venue-visit', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:55:48', 'deleted_at' => NULL),
            array('id' => '57', 'name' => 'Check our articles for outfit inspiration', 'description' => 'Check our articles for outfit inspiration', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-our-articles-for-outfit-inspiration.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-our-articles-for-outfit-inspiration', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '58', 'name' => 'Shortlist your wedding outfit', 'description' => 'Shortlist your wedding outfit', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-your-wedding-outfit.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-your-wedding-outfit', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '59', 'name' => 'Buy outfits for all pre-wedding occasions', 'description' => 'Buy outfits for all pre-wedding occasions', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'buy-outfits-for-all-pre-wedding-occasions.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'buy-outfits-for-all-pre-wedding-occasions', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '60', 'name' => 'Shortlist and buy bride\'s shoes', 'description' => 'Shortlist and buy bride\'s shoes', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-and-buy-brides-shoes.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-and-buy-brides-shoes', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '61', 'name' => 'Buy all other bridal accessories', 'description' => 'Buy all other bridal accessories', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'buy-all-other-bridal-accessories.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'buy-all-other-bridal-accessories', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '62', 'name' => 'Attend fittings for bridal lehenga and all other wedding and pre-wedding outfits', 'description' => 'Attend fittings for bridal lehenga and all other wedding and pre-wedding outfits', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'attend-fittings-for-bridal-lehenga-and-all-other-wedding-and-pre-wedding-outfits.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'attend-fittings-for-bridal-lehenga-and-all-other-wedding-and-pre-wedding-outfits', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '63', 'name' => 'Find outfit inspirations for the groom', 'description' => 'Find outfit inspirations for the groom', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'find-outfit-inspirations-for-the-groom.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'find-outfit-inspirations-for-the-groom', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '64', 'name' => 'Shortlist groom\'s outfit', 'description' => 'Shortlist groom\'s outfit', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-grooms-outfit.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-grooms-outfit', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '65', 'name' => 'Shortlist and buy shoes for the groom', 'description' => 'Shortlist and buy shoes for the groom', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-and-buy-shoes-for-the-groom.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-and-buy-shoes-for-the-groom', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '66', 'name' => 'Buy all other accessories for the groom', 'description' => 'Buy all other accessories for the groom', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'buy-all-other-accessories-for-the-groom.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'buy-all-other-accessories-for-the-groom', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '67', 'name' => 'Short list caterers', 'description' => 'Short list caterers', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'short-list-caterers.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'short-list-caterers', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '68', 'name' => 'Organize menu tasting with shortlisted caterer', 'description' => 'Organize menu tasting with shortlisted caterer', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'organize-menu-tasting-with-shortlisted-caterer.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'organize-menu-tasting-with-shortlisted-caterer', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '69', 'name' => 'Shortlist wedding cake vendor', 'description' => 'Shortlist wedding cake vendor', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-wedding-cake-vendor.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-wedding-cake-vendor', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '70', 'name' => 'Order alcohol for your wedding functions', 'description' => 'Order alcohol for your wedding functions', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'order-alcohol-for-your-wedding-functions.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'order-alcohol-for-your-wedding-functions', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '71', 'name' => 'Shortlist DJ', 'description' => 'Shortlist DJ', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-dj.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-dj', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '72', 'name' => 'Shortlist choreographer', 'description' => 'Shortlist choreographer', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-choreographer.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-choreographer', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '73', 'name' => 'Finalize and book vendors for the Baraat', 'description' => 'Finalize and book vendors for the Baraat', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'finalize-and-book-vendors-for-the-baraat.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'finalize-and-book-vendors-for-the-baraat', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '74', 'name' => 'Add a fun touch for your wedding guests by reserving a photobooth', 'description' => 'Add a fun touch for your wedding guests by reserving a photobooth', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'add-a-fun-touch-for-your-wedding-guests-by-reserving-a-photobooth.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'add-a-fun-touch-for-your-wedding-guests-by-reserving-a-photobooth', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '75', 'name' => 'Finalise music for the wedding and pre-wedding events', 'description' => 'Finalise music for the wedding and pre-wedding events', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'finalise-music-for-the-wedding-and-pre-wedding-events.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'finalise-music-for-the-wedding-and-pre-wedding-events', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '76', 'name' => ' Start looking at florists', 'description' => ' Start looking at florists', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'start-looking-at-florists.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'start-looking-at-florists', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '77', 'name' => 'Look for decor inspiration', 'description' => 'Look for decor inspiration', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'look-for-decor-inspiration.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'look-for-decor-inspiration', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2023-06-04 18:47:39', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '78', 'name' => 'Short list decor vendors', 'description' => 'Short list decor vendors', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'short-list-decor-vendors.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'short-list-decor-vendors', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '79', 'name' => 'Browse through decor vendors for the wedding and pre-wedding functions', 'description' => 'Browse through decor vendors for the wedding and pre-wedding functions', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'browse-through-decor-vendors-for-the-wedding-and-pre-wedding-functions.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'browse-through-decor-vendors-for-the-wedding-and-pre-wedding-functions', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '80', 'name' => 'Choose a bridal makeup look', 'description' => 'Choose a bridal makeup look', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'choose-a-bridal-makeup-look.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'choose-a-bridal-makeup-look', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '81', 'name' => 'Shortlist bridal makeup artists', 'description' => 'Shortlist bridal makeup artists', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-bridal-makeup-artists.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-bridal-makeup-artists', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '82', 'name' => 'Finalize all dates on which you\'ll need the bridal makeup artist', 'description' => 'Finalize all dates on which you\'ll need the bridal makeup artist', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'finalize-all-dates-on-which-youll-need-the-bridal-makeup-artist.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'finalize-all-dates-on-which-youll-need-the-bridal-makeup-artist', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '83', 'name' => 'Check for fitness program', 'description' => 'Check for fitness program', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-for-fitness-program.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-for-fitness-program', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '84', 'name' => 'Join a fitness program', 'description' => 'Join a fitness program', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'join-a-fitness-program.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'join-a-fitness-program', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '85', 'name' => 'Fix up a date for a trial with your makeup artist', 'description' => 'Fix up a date for a trial with your makeup artist', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'fix-up-a-date-for-a-trial-with-your-makeup-artist.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'fix-up-a-date-for-a-trial-with-your-makeup-artist', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '86', 'name' => 'Start pre-bridal skincare packages', 'description' => 'Start pre-bridal skincare packages', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'start-pre-bridal-skincare-packages.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'start-pre-bridal-skincare-packages', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '87', 'name' => 'Decide on hair and makeup styles', 'description' => 'Decide on hair and makeup styles', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'decide-on-hair-and-makeup-styles.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'decide-on-hair-and-makeup-styles', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '88', 'name' => 'If you want a haircut, go now!', 'description' => 'If you want a haircut, go now!', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'if-you-want-a-haircut-go-now.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'if-you-want-a-haircut-go-now', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '89', 'name' => 'Take care of your skin', 'description' => 'Take care of your skin', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'take-care-of-your-skin.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'take-care-of-your-skin', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '90', 'name' => 'Start planning your honeymoon', 'description' => 'Start planning your honeymoon', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'start-planning-your-honeymoon.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'start-planning-your-honeymoon', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '91', 'name' => 'Pack your honeymoon bags', 'description' => 'Pack your honeymoon bags', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'pack-your-honeymoon-bags.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'pack-your-honeymoon-bags', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '92', 'name' => 'Check our range of jewellery designers', 'description' => 'Check our range of jewellery designers', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'check-our-range-of-jewellery-designers.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'check-our-range-of-jewellery-designers', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '93', 'name' => 'Look for inspiration and designs for wedding rings', 'description' => 'Look for inspiration and designs for wedding rings', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'look-for-inspiration-and-designs-for-wedding-rings.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'look-for-inspiration-and-designs-for-wedding-rings', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '94', 'name' => 'Choose photography / videography services for each wedding function - candid, cinema etc.', 'description' => 'Choose photography / videography services for each wedding function - candid, cinema etc.', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'choose-photography-videography-services-for-each-wedding-function-candid-cinema-etc.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'choose-photography-videography-services-for-each-wedding-function-candid-cinema-etc', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '95', 'name' => 'Meet with a few photographers', 'description' => 'Meet with a few photographers', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'meet-with-a-few-photographers.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'meet-with-a-few-photographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '96', 'name' => 'Short list videographers', 'description' => 'Short list videographers', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'short-list-videographers.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'short-list-videographers', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '97', 'name' => 'Agree on timelines & deliverables with the photographer - when will you receive the images, in what format etc.', 'description' => 'Agree on timelines & deliverables with the photographer - when will you receive the images, in what format etc.', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'agree-on-timelines-deliverables-with-the-photographer-when-will-you-receive-the-images-in-what-format-etc.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'agree-on-timelines-deliverables-with-the-photographer-when-will-you-receive-the-images-in-what-format-etc', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '98', 'name' => 'Plan and confirm your pre-wedding shoot', 'description' => 'Plan and confirm your pre-wedding shoot', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'plan-and-confirm-your-pre-wedding-shoot.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'plan-and-confirm-your-pre-wedding-shoot', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '99', 'name' => 'Look at transportation options for your guests', 'description' => 'Look at transportation options for your guests', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'look-at-transportation-options-for-your-guests.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'look-at-transportation-options-for-your-guests', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '100', 'name' => 'Shortlist some transportation vendors', 'description' => 'Shortlist some transportation vendors', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'shortlist-some-transportation-vendors.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'shortlist-some-transportation-vendors', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '101', 'name' => 'Last minute check on the transportation', 'description' => 'Last minute check on the transportation', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'last-minute-check-on-the-transportation.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'last-minute-check-on-the-transportation', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '102', 'name' => 'Send out wedding invitations', 'description' => 'Send out wedding invitations', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'send-out-wedding-invitations.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'send-out-wedding-invitations', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '103', 'name' => 'Ghori Wala', 'description' => 'Ghori Wala for Marriage', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'ghori-wala.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'ghori-wala', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '104', 'name' => 'Delegate responsibilities', 'description' => 'Delegate responsibilities', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'delegate-responsibilities.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'delegate-responsibilities', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '105', 'name' => 'Create your wedding hashtag', 'description' => 'Create your wedding hashtag', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'create-your-wedding-hashtag.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'create-your-wedding-hashtag', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '106', 'name' => 'Organize bachelor and bachelorette parties', 'description' => 'Organize bachelor and bachelorette parties', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'organize-bachelor-and-bachelorette-parties.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'organize-bachelor-and-bachelorette-parties', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '107', 'name' => 'Make sure your wedding party has ordered their attire', 'description' => 'Make sure your wedding party has ordered their attire', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'make-sure-your-wedding-party-has-ordered-their-attire.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'make-sure-your-wedding-party-has-ordered-their-attire', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '108', 'name' => 'Buy a wedding gift for your spouse-to-be', 'description' => 'Buy a wedding gift for your spouse-to-be', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'buy-a-wedding-gift-for-your-spouse-to-be.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'buy-a-wedding-gift-for-your-spouse-to-be', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '109', 'name' => 'Think of a signature cocktail', 'description' => 'Think of a signature cocktail', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'think-of-a-signature-cocktail.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'think-of-a-signature-cocktail', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '110', 'name' => 'Contact close family and friends for Sangeet/other performances', 'description' => 'Contact close family and friends for Sangeet/other performances', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'contact-close-family-and-friends-for-sangeetother-performances.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'contact-close-family-and-friends-for-sangeetother-performances', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '111', 'name' => 'Organize youngster\'s party', 'description' => 'Organize youngster\'s party', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'organize-youngsters-party.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'organize-youngsters-party', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '112', 'name' => 'Follow up on your guest\'s arrival dates', 'description' => 'Follow up on your guest\'s arrival dates', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'follow-up-on-your-guests-arrival-dates.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'follow-up-on-your-guests-arrival-dates', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '113', 'name' => 'Write a sweet note to your partner', 'description' => 'Write a sweet note to your partner', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'write-a-sweet-note-to-your-partner.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'write-a-sweet-note-to-your-partner', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '114', 'name' => 'Pull together any last-minute essentials', 'description' => 'Pull together any last-minute essentials', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'pull-together-any-last-minute-essentials.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'pull-together-any-last-minute-essentials', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '115', 'name' => 'Confirm final details with all your vendors and put tip money aside', 'description' => 'Confirm final details with all your vendors and put tip money aside', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'confirm-final-details-with-all-your-vendors-and-put-tip-money-aside.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'confirm-final-details-with-all-your-vendors-and-put-tip-money-aside', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '116', 'name' => 'Find makeup salon options for friends and family', 'description' => 'Find makeup salon options for friends and family', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'find-makeup-salon-options-for-friends-and-family.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'find-makeup-salon-options-for-friends-and-family', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '117', 'name' => 'Prepare bridal bag to take to the venue', 'description' => 'Prepare bridal bag to take to the venue', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'prepare-bridal-bag-to-take-to-the-venue.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'prepare-bridal-bag-to-take-to-the-venue', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '118', 'name' => 'Download Wedshoots App', 'description' => 'Download Wedshoots App', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'download-wedshoots-app.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'download-wedshoots-app', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '119', 'name' => 'Download your wedding photographs from Wedshoots', 'description' => 'Download your wedding photographs from Wedshoots', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'download-your-wedding-photographs-from-wedshoots.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'download-your-wedding-photographs-from-wedshoots', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL),
            array('id' => '120', 'name' => 'Rate and review your vendors', 'description' => 'Rate and review your vendors', 'status' => '0', 'priority' => '0', 'timeline_id' => '1', 'completionDate' => '2023-04-08', 'icon' => 'rate-and-review-your-vendors.svg', 'imageOne' => 'taskDefault.png', 'slug' => 'rate-and-review-your-vendors', 'path' => NULL, 'relation' => NULL, 'parent_id' => '1', 'admin_id' => '5', 'created_at' => '2020-12-28 18:27:36', 'updated_at' => '2023-06-04 18:57:04', 'deleted_at' => NULL)
        );

        $departments = array(
            ['name' => 'Food Department'],
            ['name' => 'Transport Department'],
            ['name' => 'Accommodation Department'],
        );

        $timeline = [
            [
                'name' => 'From 10 to 12 months',
                'unit' => 'month',
                'start' => '10',
                'end' => '12',
                'duration' => 90,
                'before_after' => 0,
            ],
            [
                'name' => 'From 7 to 9 months',
                'unit' => 'month',
                'start' => '7',
                'end' => '9',
                'duration' => 90,
                'before_after' => 0,
            ],
            [
                'name' => 'From 4 to 6 months',
                'unit' => 'month',
                'start' => '4',
                'end' => '6',
                'duration' => 0,
                'duration' => 90,
                'before_after' => 0,
            ],
            [
                'name' => 'From 2 to 3 months',
                'unit' => 'month',
                'start' => '2',
                'end' => '3',
                'duration' => 60,
                'before_after' => 0,
            ],
            [
                'name' => 'The last month',
                'unit' => 'month',
                'start' => '0',
                'end' => '1',
                'duration' => 30,
                'before_after' => 0,
            ],
            [
                'name' => '2 weeks',
                'unit' => 'week',
                'start' => '0',
                'end' => '2',
                'duration' => 14,
                'before_after' => 0,
            ],
            [
                'name' => 'Last week',
                'unit' => 'week',
                'start' => '0',
                'end' => '1',
                'duration' => 7,
                'before_after' => 0,
            ],
            [
                'name' => 'After the wedding',
                'unit' => 'week',
                // 'start' => '0',
                // 'end' => '0',
                // 'duration' => 0,
                'before_after' => 1,
            ],
        ];


        foreach ($timeline as $key => $val) {
            TaskTimeline::create($val);
        }

        foreach ($taskcats as $key => $val) {
            TaskMaster::create($val);
        }

        foreach ($departments as $key => $val) {
            MemberDepartment::create($val);
        }
    }
}
