@extends('layouts.app')

@section('content')
<landing-terms-condition></landing-terms-condition>
{{-- <!-- <div class="container">
    <h3> Terms & Conditions </h3>

    <h4>1. Acknowledgments and acceptance of Terms of Service</h4>
    <p> The services offered at www.happywed.in and any subdomains, are provided to you under the terms and conditions of this www.happywed.in Terms of Service ("Terms of Service"), and any operating rules or policies that may be published by Www.happywed.in at the URL: www.happywed.in(the "Service"). The Terms of Service comprises the entire agreement between you and Www.happywed.in and supersedes all prior agreements between the parties regarding the subject matter contained herein.
        BY COMPLETING THE REGISTRATION PROCESS, OR USING www.happywed.in , USER AGREES TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS HEREIN. You may continue to use www.happywed.in as long as you adhere to these Terms of Service.</p>

    <h4> 2. Services void where prohibited </h4>
    <p> Use of the Services is void where prohibited. By using this Service, you represent and warrant that you have the right, authority, and capacity to enter into this Agreement and to abide by all the Terms and Conditions of this Agreement.</p>

    <h4> 3. Registration </h4>
    <p> You are required to register with Happy Wedding if you want to write a review, create profiles of gift recipients, create and access your reminders, and view and edit your profile. In order to register with Happy Wedding you must supply a valid email address, which will be used as a unique identifier for your account, and a password.</p>

    <h4> 4. Description of service </h4>
    <p>www.happywed.in provides users with a variety of online services, including but not limited to: www.happywed.in will suggest gift for couple and family based on certain information you provide to us about the recipient such as age, relationship with you, and the occasion. You may further filter gift ideas based on a specified price range, the recipient’s personality, the type of gift, approximate delivery date, mode of payment, gift category, and city of the recipient. Www.happywed.in also provide the facility of creating wedding website to couple along with a complete information about the wedding service and wedding related products facilitators like banquets , catering etc a complete advertising model.
    </p>

    <h4> 5. Limitation of liability </h4>
    <p> By using www.happywed.in , you agree and understand that injuries and damages can occur by the use of such products, either as a result of negligence or because of other reasons. notwithstanding anything to the contrary herein, to the fullest extent allowed by law, you agree to waive and discharge all claims, release Happy Wedding from all liability and indemnify and hold harmless Happy Wedding its subsidiaries, affiliates, officers, agents, and other partners and employees, from any and all liability on account of, or in any way resulting from injuries and damages in any way connected with any products purchased by way of using the website. You agree and understand and intend that this assumption of risk and release is binding upon you and your heirs, executors, agents, administrators and assigns, and includes any minors accompanying user at the events.</p>

    <h4> 6. Content </h4>
    <p> You are solely responsible for any data, text, graphics, messages, or other materials ("Content") which is transmitted, posted, or distributed by you through the Service, including but not limited to the contents of your information or reviews. All Content posted by you is your sole responsibility. www.happywed.in does not control the Content posted by users such as yourself via the Service and, as such, does not guarantee the accuracy, integrity or quality of such Content. Under no circumstances will Www.happywed.in be liable in any way for any Content posted by any user or third party, including, but not limited to, liability for any errors or omissions in any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted via the Service. Subject to the terms of www.happywed.in Privacy Policy, you agree if you post any Content on the www.happywed.in Site, you grant to www.happywed.in, and its successors and assigns, a non-exclusive, worldwide, royalty-free, perpetual, non-revocable license, in and to the Content, to distribute, display, modify, redistribute, sublicense and reproduce such Content to other users of the Service and to third parties with whom www.happywed.in has a relationship. You also grant Www.happywed.in the right to authorize the downloading and printing in whole or in part of any Content that you post to the www.happywed.in.</p>

    <h4>7. Copyright policy/infringing material</h4>
    <p> You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information owned or controlled by someone else without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the www.happywed.in Service without your permission or in any way that constitutes copyright infringement, please provide Www.happywed.in with the following information: a description of the copyrighted work that you claim has been infringed; a description of where the material you claim is infringing is located on the Www.happywed.in Service; your address, telephone number, and email address; and a written statement by you stating that you have a good faith belief that the disputed use is not authorized by you, your agent, or the law; and a statement by you, made under penalty of perjury, that you own the claimed infringing material together with any evidence of such ownership. Please contact www.happywed.in .</p>

    <h4> 8. No "SPAMMING" </h4>
    <p>
        You must not use any feature of the Www.happywed.in Service for chain letters, junk mail, or "Spamming" nor make any use of the distribution lists in a manner involving any person who has not given specific permission to be included in such a process. An email advertisement which is (a) addressed to a recipient with whom you do not have an existing business or personal relationship and (b) is not sent at the request of or with the express consent of the recipient to receive such communications from you ("Spam" or "Spamming") is strictly prohibited by www.happywed.in . If you use any feature of the www.happywed.in Service for the purpose of sending Spam, www.happywed.in reserves the right to immediately terminate your access to the www.happywed.in Service and to seek appropriate legal recourse as necessary. If you believe that other users are using the www.happywed.in Service for Spam, please notify www.happywed.in using the Report Abuse form that is available by clicking the "Report Abuse" link under a user's product review.
    </p>

    <h4> 9. Notices </h4>
    <p> www.happywed.in may give notice to you by e-mail, a posting on the Site, or other reasonable means. You must give notice to www.happywed.in in writing via e-mail or as otherwise expressly provided by www.happywed.in may broadcast, distribute or display notices or messages through the www.happywed.in Service to inform you of changes to the TERMS OF SERVICE, the Service, the Privacy Policy or other matters of importance. Such broadcast, distributions or displays of information shall constitute notice to you.</p>

    <h4> 10. Privacy policy </h4>
    <p> It is www.happywed.in policy to respect the privacy of its users. www.happywed.in policies with regard to Personally Identifiable Information it collects from you, what information third parties affiliated with www.happywed.in collect from you and how that information is used is governed by the www.happywed.in Privacy Policy</p>

    <h4>11. Security </h4>
    <p>You are solely responsible for maintaining the confidentiality of your password and account, and for any and all activities that occur under your account. You agree to notify Www.happywed.in immediately of any unauthorized use of your account or any other breach of security known to you. You must promptly inform www.happywed.in of actual or apparent breaches of security, such as loss, theft, or authorized disclosure or use of a user account or password. Until is notified of a breach in security, you will remain liable for any unauthorized use of the www.happywed.in Service through your account. In consideration for using the Www.happywed.in Service, you agree to: (1) provide certain current, complete, and accurate information about you when prompted to do so by the Service, and (2) maintain and update this information as required to keep it current, complete and accurate. If any information provided by you during your original registration is inaccurate, Www.happywed.in reserves the right to terminate your account immediately and your right to use the Www.happywed.in Service.</p>

    <h4> 12. No resale or commercial use, abuse of the service </h4>
    <p> Your right to use the www.happywed.in Service is personal to you. You agree not to resell or make any commercial use of the www.happywed.in Service without the express consent of www.happywed.in . You may not create bots or other computer generated automatic tools to abuse the www.happywed.in Service in any manner. Use that constitutes abuse shall be determined by www.happywed.in in its sole discretion. www.happywed.in reserves the right to terminate your account if www.happywed.in determines you have not complied with these </p>


    <h4> 13. User conduct </h4>
    <p> www.happywed.in reserves the right, but does not assume the responsibility, to monitor or review your conduct on the www.happywed.in Site. Your use of the www.happywed.in Service is subject to all applicable local, state, national and international laws and regulations. In using the Happy Wedding Service you agree not to :
        Use the Www.happywed.in Service for illegal purposes Interfere or disrupt networks connected to the Www.happywed.in Service or violate the regulations, policies or procedures of such networks Use the Www.happywed.in Service in connection with chain letters, junk mail, surveys, contests, pyramid schemes, or use any distribution lists including any person who has not given specific permission to be included in such a process (commercial or otherwise) Harvest or otherwise collect information about other users, including e-mail addresses, without their consent Transmit through the Www.happywed.in Service any unlawful, harassing, defamatory, abusive, threatening, harmful, vulgar, obscene, sexually explicit, or otherwise objectionable material of any kind or nature Invade another's privacy or violate rights of publicity or intellectual property rights (including but not limited to copyright, trademark and patent rights) while using the Www.happywed.in Service Transmit through the Www.happywed.in Service any material that encourages conduct that could constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national or international law or regulation Interfere with another User's use and enjoyment of the Www.happywed.in Service Defame, abuse, harass, stalk, threaten or violate the legal rights (such as rights of privacy and publicity) of any other user Create a false identity for the purpose of misleading others as to your identity or the origin of a message Use, download or otherwise copy, or provide (whether or not for a fee) to a person or entity that is not a user of the www.happywed.in Service any directory of www.happywed.in users or usage information or any portion thereof other than in the context of your use of the Service as permitted under these Terms of Service Transmit or upload any material that contains viruses, trojan horses, worms, time bombs, cancel bots, or any other harmful or deleterious programs Attempt to gain unauthorized access to the Service, other accounts, computer systems or networks connected to the Service, through password mining or any other means; or Engage in any other conduct which, in Www.happywed.in\’s sole discretion, is considered inappropriate, unauthorized or objectionable. of Service </p>

    <h4> 14. Indemnification</h4>
    <p>
        You agree to indemnify and hold www.happywed.in , its parent, subsidiary, affiliate, officers, employees, agents, directors, successors and assigns harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your use of the www.happywed.in Service, the violation of these Terms of Service by you, the infringement by you (or other user of the Service using your account) of any intellectual property or other right of any person or entity or violation of any federal, state or local law or regulation.
    </p>
    <h4> 15. Termination </h4>
    <p> You may terminate your participation in the www.happywed.in Service with or without cause at any time and effective immediately. www.happywed.in may terminate the www.happywed.in Service or your use of the Service with or without cause at any time and effective immediately, at www.happywed.in ’s sole discretion, by immediate termination of your use of the www.happywed.in Service should your conduct fail to conform to the terms and conditions of these Terms of Service. www.happywed.in shall not be liable to you or any third party for termination of the www.happywed.in Service or termination of your use of the www.happywed.in Service. Should you object to any terms and conditions of the Terms of Service or any subsequent modifications www.happywed.in makes to the Terms of Service or become dissatisfied with the www.happywed.in Service in any way, your only recourse is to immediately: (1) discontinue use of the Www.happywed.in Service; and (2) notify Www.happywed.in of your termination and, at your discretion, notify Www.happywed.in of the reasons for your termination. Upon termination of your use of the Www.happywed.in Service, your right to use the Www.happywed.in Service shall cease immediately. You shall have no right and Www.happywed.in will have no obligation thereafter to forward any unread or unsent messages to your or any third party on your behalf. Sections 2, 5, 6, 7, 10, 11, 14, 15, 16, 19, 20 and 21 shall survive termination of the Terms of Service.</p>

    <h4> 16. Transactions with organizations or individuals </h4>

    <p> www.happywed.in shall not be liable for your interactions with any merchants, retailers and/or individuals found on or through the www.happywed.in Service. This includes, but is not limited to, payment and delivery of goods and services, and any other terms, conditions, warranties or representations associated with such dealings. These dealings are solely between you and such merchants, retailers and/or individuals. www.happywed.in is under no obligation to become involved in disputes between participants on the happywed.in Service, or between participants on the www.happywed.in Service and any third party.</p>

    <h4> 17. Links to third party sites </h4>
    <p> Any web sites that are accessible via links included within the Www.happywed.in Service that take you out of the www.happywed.in Service are not under www.happywed.in control and www.happywed.in shall not be responsible for the content, products or services of any linked website. All such websites shall be subject to the policies and procedures of the owner of such websites. We encourage you to read those policies and know your rights under any web site you visit.</p>

    <h4> 18. Violation of terms by other users </h4>
    <p>
        www.happywed.in asks that you participate in ensuring that all users follow the terms of these Terms of Service by reporting any user reviews or other postings or messages that violate these terms. To report a violation of these Terms of Service, please email us at or click on the Report Abuse link under user reviews.
    </p>

    <h4> 19. Disclaimer of warranties </h4>

    You expressly agree that your use of the www.happywed.in service is at your sole risk. The www.happywed.in service is provided on an "as is" and "as available" basis. Www.happywed.in expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. www.happywed.in makes no warranty that its service will meet your requirements, or that its service will be uninterrupted, timely, secure, or error free. www.happywed.in makes no warranty as to the results that may be obtained from the use of the service or as to the accuracy or reliability of any information obtained through the service or that defects in the software will be corrected. You acknowledge that www.happywed.in does not control content, information, products or services offered by advertisers, third parties or other users on or through the service, including but not limited to information, products, or services provided by license to www.happywed.in from third parties or content provided by other users. Www.happywed.in assumes no responsibility for and makes no warranty or representation as to the accuracy, currency, completeness, reliability, usefulness or decency of content or products distributed or made available by third parties (including but not limited to advertisers and users) through the www.happywed.in service. You will be solely responsible for any damage to your computer system or loss of data that results from your attempt to download any material from the www.happywed.in service. Www.happywed.in makes no warranty regarding any goods or services purchased or obtained through its service or any transactions entered into through its service. No advice or information, whether oral or written, obtained by you from www.happywed.in or through the www.happywed.in service shall create any warranty not expressly made herein. Some jurisdictions do not allow the exclusion of certain warranties, therefore some of the above exclusions may not apply to you.

    <h4> 20. Limitation of liability </h4>

    www.happywed.in shall not be liable for any indirect, incidental, special or consequential damages, including but not limited to damages for loss of profits, use, data or other intangibles, even if www.happywed.in has been advised of the possibility of such damages, resulting from the (i) use or the inability to use the service; (ii) cost of procurement of substitute goods and services; (iii) any goods or services purchased or obtained or content received or transactions entered into with www.happywed.in or a third party through the use of the www.happywed.in service; (iv) or unauthorized access to your account or alteration of your account or data. You specifically agree that www.happywed.in is not responsible or liable to you or anyone else for any unlawful, harassing, defamatory, abusive, threatening, harmful, vulgar, obscene, sexually explicit or otherwise objectionable conduct or speech of any other party on or through the www.happywed.in service, or for any infringement or violation of your rights by any other party, including but not limited to intellectual property rights, rights of publicity, or rights of privacy. Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages; therefore some of the above limitations may not apply to some users.

    <h4> 21. Reviews on Vendor profiles </h4>

    Reviews written for vendors on their Happy Wedding profile are a very important tool for new couples as well as vendors. We therefore take utmost care to uphold the integrity & credibility of reviews on our platform.
    Note that Happy Wedding cannot & does not verify and confirm to every statement written in the reviews on vendor profiles. However, we maintain a fair investigation & verification process of the reviews once reported to ensure that reviews on Happy Wedding are posted by genuine clients of vendors and that they follow our terms.
    Happy Wedding reserves the right to disable a review of the reviewer who has been proven to not hire the vendor through involvement of Happy Wedding, for any reason. Happy Wedding has the sole discretion to decide whether reported reviews are to be further investigated or not.

    <h4> 22. Modifications to the service and to terms of service </h4>
    <p>
    Www.happywed.in reserves the right to modify or discontinue the Www.happywed.in Service with or without notice to you. happywed.in shall not be liable to you if Www.happywed.in modifies or discontinues its Service. Www.happywed.in may change the terms and conditions of the Terms of Service at any time in its sole discretion. In the event of any material or substantial change in the terms and conditions of these Terms of Service, Www.happywed.in may notify you via e-mail, and/or by posting an announcement of the changes together with a link to the new Terms of Service on the Www.happywed.in Service. By using the Www.happywed.in Service after any change in the Terms of Service you acknowledge and accept changes to the Terms of Service
    <p>
        
</div> --> --}}
@endsection
